# Minimal Walker Configuration for Maximum Performance
# Copy this to config.toml for optimal performance

app_launch_prefix = "sh -c "
terminal_title_flag = ""
locale = ""
close_when_open = true
theme = "omarchy-default"
theme_base = []
theme_location = ["~/.local/share/omarchy/default/walker/themes/"]
monitor = ""
hotreload_theme = false
as_window = false
timeout = 0
disable_click_to_close = false
force_keyboard_focus = true

[keys]
accept_typeahead = ["tab"]
trigger_labels = "lalt"
next = ["down"]
prev = ["up"]
close = ["esc"]
remove_from_history = ["shift backspace"]
resume_query = ["ctrl r"]
toggle_exact_search = ["ctrl m"]

[keys.activation_modifiers]
keep_open = "shift"
alternate = "alt"

[events]
on_activate = ""
on_selection = ""
on_exit = ""
on_launch = ""
on_query_change = ""

[list]
dynamic_sub = true
keyboard_scroll_style = "emacs"
max_entries = 20  # Minimal for best performance
show_initial_entries = true
single_click = true
visibility_threshold = 10  # Minimal for best performance
placeholder = "No Results"

[search]
argument_delimiter = "#"
placeholder = " Search..."
delay = 0
resume_last_query = false

[activation_mode]
labels = "jkl;asdf"

# Only essential modules enabled for maximum performance
[builtins.applications]
weight = 5
name = "applications"
placeholder = " Search..."
prioritize_new = false
hide_actions_with_empty_query = true
context_aware = false
refresh = false  # Critical for performance
show_sub_when_single = false
show_icon_when_single = true
show_generic = true
history = false
icon = ""
hidden = false

[builtins.applications.actions]
enabled = false
hide_category = true
hide_without_query = true

[builtins.calc]
require_number = true
weight = 5
name = "Calculator"
icon = "accessories-calculator"
placeholder = "Calculator"
min_chars = 3
prefix = "="

[builtins.emojis]
exec = "wl-copy"
weight = 5
name = "Emojis"
placeholder = "Emojis"
switcher_only = true
history = true
typeahead = true
show_unqualified = false
prefix = ":"

[builtins.switcher]
weight = 5
name = "switcher"
placeholder = "Switcher"
prefix = "/" 